baseurl = "https://blog.yuyasvx.me/"
languageCode = "ja"
title = "Blog Extended"
theme = "blogextended-original"
googleAnalytics = ""
disqusShortname = ""
HasCJKLanguage = true

[author]
    # If you want to display author information set these
    # This is Optional values
    name = "YUYASVX"

    # Please set account ids
    # This is Optional values

[params]
    [params.sharebutton]
        # If you want to display share buttons set these
        # This is Optional values
        twitter  = false
        facebook = false
        tumblr   = false
        # hatena   = true # hatena is Japanese social media
        google   = false
        pocket   = false
        # Please set id when you want to display facebook
        facebookAppId = "yourappid"

    [params.adsense]
        # If you want to display Google adsense set these
        # This is Optional values
        # 1. Create file written of the adsense tag into the directory "layouts/partials"
        # 2. Please set file path name omitted "layouts/partials"
        # sidebar = "adsense/sidebar.html"
        # content = "adsense/content.html"

[taxonomies]
  # 分類名 = "Frontmatterの属性名" というフォーマットで定義する。属性名がurlの一部になる。

  tag = "tags"
  # タグはいくつも列挙できますが、できるだけ5つ以内にまとめる事。それ以上増えた場合、テーマが崩れるかも

  category = "categories"
  # カテゴリは1つだけ設定する事 ※じゃあなんで複数形なのとか聞かない事。2つ以上設定しても、1つ目の要素しか取得しません。

  monthlyarchives = "month"
  # 月別アーカイブ用。

  series = "series"
  # 月別アーカイブ用。

[permalinks]
  # セクション名 = "/セクション名/hoge/hoge" というフォーマットで定義する
  post = "/post/:year/:month/:slug/"

# [outputFormats.json]
#   mediaType = "application/json"
#   baseName = "feed"
#   isPlainText = true

[outputs]
  home = ["rss","JSON"]
  section = ["JSON"]
  # taxonomyTerm = ["JSON"]
  taxonomy = ["JSON"]
  page = ["JSON"]
