# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Blog Extended Original"
license = "MIT"
licenselink = "https://github.com/yuyasvx/yourtheme/blob/master/LICENSE.md"
description = ""
homepage = "http://yuyasvx.github.io/"
tags = ["yuyasvx"]
features = ["a", "b"]
min_version = 0.40

[author]
  name = "YUYA SASAKI"
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
